CREATE TABLE IF NOT EXISTS provincias (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS municipios (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  provincia_id INTEGER REFERENCES provincias(id)
);

CREATE TABLE IF NOT EXISTS peticiones (
  id SERIAL PRIMARY KEY,
  descripcion TEXT NOT NULL,
  municipio_id INTEGER REFERENCES municipios(id)
);

INSERT INTO provincias (id, nombre) VALUES (1, 'ALTAGRACIA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (1, 'BAYAHIBE (DM)', 1);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (2, 'BOCA DE YUMA (DM)', 1);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (3, 'HIGUEY', 1);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (4, 'LA LAGUNA DE NISIBON (DM)', 1);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (5, 'LA OTRA BANDA (DM)', 1);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (6, 'SAN RAFAEL DEL YUMA', 1);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (7, 'TURISTICO VERON PUNTA CANA (DM)', 1);
INSERT INTO provincias (id, nombre) VALUES (2, 'AZUA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (8, 'AMIAMA GOMEZ (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (9, 'AZUA', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (10, 'BARRERAS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (11, 'BARRO ARRIBA (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (12, 'DOÑA EMMA BALAGUER VDA. VALLEJO', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (13, 'EL ROSARIO (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (14, 'ESTEBANIA', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (15, 'GUAYABAL', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (16, 'HATO NUEVO CORTES (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (17, 'LA SIEMBRA (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (18, 'LAS BARIAS-LA ESTANCIA (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (19, 'LAS CHARCAS', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (20, 'LAS CLAVELLINAS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (21, 'LAS LAGUNAS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (22, 'LAS LOMAS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (23, 'LAS YAYAS DE VIAJAMA', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (24, 'LOS FRIOS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (25, 'LOS JOVILLOS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (26, 'LOS TOROS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (27, 'MONTE BONITO (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (28, 'PADRE LAS CASAS', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (29, 'PALMAR DE OCOA (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (30, 'PERALTA', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (31, 'PROYECTO #4 (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (32, 'PROYECTO 2-C (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (33, 'PROYECTO D-1 GANADERO (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (34, 'PUEBLO VIEJO', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (35, 'PUERTO VIEJO-LOS NEGROS (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (36, 'SABANA YEGUA', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (37, 'TABARA ABAJO (DM)', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (38, 'TABARA ARRIBA', 2);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (39, 'VILLARPANDO (DM)', 2);
INSERT INTO provincias (id, nombre) VALUES (3, 'BAHORUCO');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (40, 'CABEZA DE TORO (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (41, 'EL PALMAR (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (42, 'EL SALADO', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (43, 'GALVAN', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (44, 'LAS CLAVELLINAS (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (45, 'LOS RIOS', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (46, 'MENA (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (47, 'MONSERRAT (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (48, 'NEYBA', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (49, 'SANTA BARBARA EL 6', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (50, 'SANTANA (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (51, 'TAMAYO', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (52, 'UVILLA (DM)', 3);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (53, 'VILLA JARAGUA', 3);
INSERT INTO provincias (id, nombre) VALUES (4, 'BARAHONA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (54, 'ARROYO DULCE (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (55, 'BAHORUCO (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (56, 'BARAHONA', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (57, 'CABRAL', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (58, 'CANOA (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (59, 'EL CACHON (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (60, 'EL PEÑON', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (61, 'ENRIQUILLO', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (62, 'FONDO NEGRO (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (63, 'FUNDACION', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (64, 'JAQUIMEYES', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (65, 'LA CIENAGA', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (66, 'LA GUAZARA (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (67, 'LAS SALINAS', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (68, 'LOS PATOS (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (69, 'PALO ALTO (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (70, 'PARAISO', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (71, 'PESCADERIA (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (72, 'POLO', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (73, 'QUITA CORAZA (DM)', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (74, 'VICENTE NOBLE', 4);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (75, 'VILLA CENTRAL', 4);
INSERT INTO provincias (id, nombre) VALUES (5, 'DAJABÓN');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (76, 'CAÑONGO (DM)', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (77, 'CAPOTILLO (DM)', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (78, 'DAJABON', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (79, 'EL PINO', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (80, 'LOMA DE CABRERA', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (81, 'MANUEL BUENO (DM)', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (82, 'PARTIDO', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (83, 'RESTAURACION', 5);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (84, 'SANTIAGO DE LA CRUZ (DM)', 5);
INSERT INTO provincias (id, nombre) VALUES (6, 'DISTRITO NACIONAL');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (85, 'DISTRITO NACIONAL', 6);
INSERT INTO provincias (id, nombre) VALUES (7, 'DUARTE');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (86, 'AGUA SANTA DEL YUNA (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (87, 'ARENOSO', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (88, 'BARRAQUITO (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (89, 'CASTILLO', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (90, 'CENOVI (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (91, 'CRISTO REY DE GUARAGUAO (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (92, 'DON ANTONIO GUZMAN FERNANDEZ (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (93, 'EL AGUACATE (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (94, 'EUGENIO MARIA DE HOSTOS', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (95, 'JAYA (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (96, 'LA PEÑA (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (97, 'LAS COLES (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (98, 'LAS GUARANAS', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (99, 'LAS TARANAS (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (100, 'PIMENTEL', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (101, 'SABANA GRANDE (DM)', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (102, 'SAN FRANCISCO DE MACORIS', 7);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (103, 'VILLA RIVA', 7);
INSERT INTO provincias (id, nombre) VALUES (8, 'EL SEYBO');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (104, 'EL JOVERO (EL CEDRO) (DM)', 8);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (105, 'EL SEIBO', 8);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (106, 'LA GINA (DM)', 8);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (107, 'MICHES', 8);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (108, 'PEDRO SANCHEZ (DM)', 8);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (109, 'SAN FRANCISCO-VICENTILLO (DM)', 8);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (110, 'SANTA LUCIA-LA HIGUERA (DM)', 8);
INSERT INTO provincias (id, nombre) VALUES (9, 'ELÍAS PIÑA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (111, 'BANICA', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (112, 'COMENDADOR', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (113, 'EL LLANO', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (114, 'GUANITO (DM)', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (115, 'GUAYABO (DM)', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (116, 'HONDO VALLE', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (117, 'JUAN SANTIAGO', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (118, 'PEDRO SANTANA', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (119, 'RANCHO DE LA GUARDIA (DM)', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (120, 'RIO LIMPIO (DM)', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (121, 'SABANA CRUZ (DM)', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (122, 'SABANA HIGUERO (DM)', 9);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (123, 'SABANA LARGA (DM)', 9);
INSERT INTO provincias (id, nombre) VALUES (10, 'ESPAILLAT');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (124, 'CANCA LA REYNA (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (125, 'CAYETANO GERMOSEN', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (126, 'GASPAR HERNANDEZ', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (127, 'HIGUERITO (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (128, 'JAMAO AL NORTE', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (129, 'JOBA ARRIBA (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (130, 'JOSE CONTRERAS (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (131, 'JUAN LOPEZ ABAJO (EL MAMEY) (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (132, 'LAS LAGUNAS ABAJO (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (133, 'MOCA', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (134, 'MONTE DE LA JAGUA (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (135, 'ORTEGA (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (136, 'SAN VICTOR (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (137, 'VERAGUA (DM)', 10);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (138, 'VILLA MAGANTE (DM)', 10);
INSERT INTO provincias (id, nombre) VALUES (11, 'HATO MAYOR');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (139, 'EL VALLE', 11);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (140, 'ELUPINA CORDERO DE LAS CAÑITAS (DM)', 11);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (141, 'GUAYABO DULCE (DM)', 11);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (142, 'HATO MAYOR', 11);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (143, 'MATA PALACIO (DM)', 11);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (144, 'SABANA DE LA MAR', 11);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (145, 'YERBA BUENA (DM)', 11);
INSERT INTO provincias (id, nombre) VALUES (12, 'HERMANAS MIRABAL');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (146, 'BLANCO (DM)', 12);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (147, 'MONTE LLANO (JAMAO AFUERA) (DM)', 12);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (148, 'SALCEDO', 12);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (149, 'TENARES', 12);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (150, 'VILLA TAPIA', 12);
INSERT INTO provincias (id, nombre) VALUES (13, 'INDEPENDENCIA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (151, 'BATEY 8 (DM)', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (152, 'BOCA DE CACHON (DM)', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (153, 'CRISTOBAL', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (154, 'DUVERGE', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (155, 'EL LIMON (DM)', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (156, 'GUAYABAL (DM)', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (157, 'JIMANI', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (158, 'LA COLONIA (DM)', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (159, 'LA DESCUBIERTA', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (160, 'MELLA', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (161, 'POSTRER RIO', 13);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (162, 'VENGAN A VER (DM)', 13);
INSERT INTO provincias (id, nombre) VALUES (14, 'LA ROMANA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (163, 'CUMAYASA (DM)', 14);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (164, 'GUAYMATE', 14);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (165, 'LA CALETA (DM)', 14);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (166, 'LA ROMANA', 14);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (167, 'VILLA HERMOSA', 14);
INSERT INTO provincias (id, nombre) VALUES (15, 'LA VEGA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (168, 'BUENA VISTA (DM)', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (169, 'CONSTANZA', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (170, 'EL RANCHITO (DM)', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (171, 'JARABACOA', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (172, 'JIMA ABAJO', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (173, 'LA SABINA (DM)', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (174, 'LA VEGA', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (175, 'MANABAO (DM)', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (176, 'RINCON (DM)', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (177, 'RIO VERDE ARRIBA (DM)', 15);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (178, 'TIREO ARRIBA (DM)', 15);
INSERT INTO provincias (id, nombre) VALUES (16, 'MARIA TRINIDAD SÁNCHEZ');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (179, 'ARROYO AL MEDIO (DM)', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (180, 'ARROYO SALADO (DM)', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (181, 'CABRERA', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (182, 'EL FACTOR', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (183, 'EL POZO (DM)', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (184, 'LA ENTRADA (DM)', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (185, 'LAS GORDAS (DM)', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (186, 'NAGUA', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (187, 'RIO SAN JUAN', 16);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (188, 'SAN JOSE DE MATANZAS (DM)', 16);
INSERT INTO provincias (id, nombre) VALUES (17, 'MONSEÑOR NOUEL');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (189, 'ARROYO TORO-MASIPEDRO (DM)', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (190, 'BONAO', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (191, 'JAYACO (DM)', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (192, 'JUAN ADRIAN (DM)', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (193, 'JUMA BEJUCAL (DM)', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (194, 'LA SALVIA-LOS QUEMADOS (DM)', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (195, 'MAIMON', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (196, 'PIEDRA BLANCA', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (197, 'SABANA DEL PUERTO (DM)', 17);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (198, 'VILLA SONADOR (DM)', 17);
INSERT INTO provincias (id, nombre) VALUES (18, 'MONTE PLATA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (199, 'BAYAGUANA', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (200, 'BOYA-EL CENTRO (DM)', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (201, 'CHIRINO (DM)', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (202, 'DON JUAN (DM)', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (203, 'GONZALO (DM)', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (204, 'LOS BOTADOS (DM)', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (205, 'MAJAGUAL (DM)', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (206, 'MONTE PLATA', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (207, 'PERALVILLO', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (208, 'SABANA GRANDE DE BOYA', 18);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (209, 'YAMASA', 18);
INSERT INTO provincias (id, nombre) VALUES (19, 'MONTECRISTI');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (210, 'CANA CHAPETON (DM)', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (211, 'CASTAÑUELAS', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (212, 'GUAYUBIN', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (213, 'HATILLO PALMA (DM)', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (214, 'LAS MATAS DE SANTA CRUZ', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (215, 'MONTECRISTI', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (216, 'PALO VERDE (EL AHOGADO) (DM)', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (217, 'PEPILLO SALCEDO', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (218, 'VILLA ELISA (DM)', 19);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (219, 'VILLA VASQUEZ', 19);
INSERT INTO provincias (id, nombre) VALUES (20, 'PEDERNALES');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (220, 'JOSE FRANCISCO PEÑA GOMEZ (DM)', 20);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (221, 'JUANCHO (DM)', 20);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (222, 'OVIEDO', 20);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (223, 'PEDERNALES', 20);
INSERT INTO provincias (id, nombre) VALUES (21, 'PERAVIA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (224, 'BANI', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (225, 'EL CARRETON (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (226, 'EL LIMONAL (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (227, 'LA CATALINA (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (228, 'LAS BARIAS (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (229, 'MATANZAS (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (230, 'NIZAO', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (231, 'PAYA (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (232, 'PIZARRETE (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (233, 'SABANA BUEY (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (234, 'SANTANA (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (235, 'VILLA FUNDACION (DM)', 21);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (236, 'VILLA SOMBRERO (DM)', 21);
INSERT INTO provincias (id, nombre) VALUES (22, 'PUERTO PLATA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (237, 'ALTAMIRA', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (238, 'BELLOSO (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (239, 'CABARETE (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (240, 'ESTERO HONDO (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (241, 'ESTRECHO DE LUPERON OMAR BROSS (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (242, 'GUALEPE', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (243, 'GUANANICO', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (244, 'IMBERT', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (245, 'LA ISABELA (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (246, 'LA JAIBA (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (247, 'LOS HIDALGOS', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (248, 'LUPERON', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (249, 'MAIMON (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (250, 'NAVAS (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (251, 'PUERTO PLATA', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (252, 'RIO GRANDE (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (253, 'SABANETA DE YASICA (DM)', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (254, 'SOSUA', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (255, 'VILLA ISABELA', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (256, 'VILLA MONTELLANO', 22);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (257, 'YASICA ARRIBA (DM)', 22);
INSERT INTO provincias (id, nombre) VALUES (23, 'SAMANÁ');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (258, 'ARROYO BARRIL (DM)', 23);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (259, 'EL LIMON (DM)', 23);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (260, 'LAS GALERAS (DM)', 23);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (261, 'LAS TERRENAS', 23);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (262, 'SAMANA', 23);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (263, 'SANCHEZ', 23);
INSERT INTO provincias (id, nombre) VALUES (24, 'SAN CRISTÓBAL');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (264, 'BAJOS DE HAINA', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (265, 'CAMBITA EL PUEBLECITO (DM)', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (266, 'CAMBITA GARABITOS', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (267, 'EL CARRIL (DM)', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (268, 'HATO DAMAS (DM)', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (269, 'LA CUCHILLA (DM)', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (270, 'LOS CACAOS', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (271, 'MEDINA (DM)', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (272, 'SABANA GRANDE DE PALENQUE', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (273, 'SAN CRISTOBAL', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (274, 'SAN GREGORIO DE NIGUA', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (275, 'SAN JOSE-PINO HERRADO-EL PUERTO(DM)', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (276, 'VILLA ALTAGRACIA', 24);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (277, 'YAGUATE', 24);
INSERT INTO provincias (id, nombre) VALUES (25, 'SAN JOSE DE OCOA');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (278, 'EL NARANJAL (DM)', 25);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (279, 'EL PINAR (DM)', 25);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (280, 'LA CIENAGA (DM)', 25);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (281, 'NIZAO-LAS AUYAMAS (DM)', 25);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (282, 'RANCHO ARRIBA', 25);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (283, 'SABANA LARGA', 25);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (284, 'SAN JOSE DE OCOA', 25);
INSERT INTO provincias (id, nombre) VALUES (26, 'SAN JUAN');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (285, 'ARROYO CANO (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (286, 'BATISTA (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (287, 'BOHECHIO', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (288, 'CARRERA DE YEGUAS (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (289, 'DERRUMBADERO (EL NUEVO BRAZIL) (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (290, 'EL CERCADO', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (291, 'EL ROSARIO (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (292, 'GUANITO (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (293, 'HATO DEL PADRE (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (294, 'JINOVA (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (295, 'JORGILLO (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (296, 'JUAN DE HERRERA', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (297, 'LA JAGUA (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (298, 'LA ZANJA', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (299, 'LAS CHARCAS DE MARIA NOVAS (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (300, 'LAS MAGUANAS-HATO NUEVO (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (301, 'LAS MATAS DE FARFAN', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (302, 'MATAYAYA (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (303, 'PEDRO CORTO (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (304, 'SABANA ALTA (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (305, 'SABANETA (DM)', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (306, 'SAN JUAN DE LA MAGUANA', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (307, 'VALLEJUELO', 26);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (308, 'YAQUE (BUENA VISTA) (DM)', 26);
INSERT INTO provincias (id, nombre) VALUES (27, 'SAN PEDRO DE MACORÍS');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (309, 'CONSUELO', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (310, 'EL PUERTO (DM)', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (311, 'GAUTIER (DM)', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (312, 'GUAYACANES', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (313, 'LOS LLANOS', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (314, 'QUISQUEYA', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (315, 'RAMON SANTANA', 27);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (316, 'SAN PEDRO DE MACORIS', 27);
INSERT INTO provincias (id, nombre) VALUES (28, 'SÁNCHEZ RAMIREZ');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (317, 'ANGELINA (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (318, 'CABALLERO (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (319, 'CEVICOS', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (320, 'COMEDERO ARRIBA (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (321, 'COTUI', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (322, 'FANTINO', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (323, 'HERNANDO ALONZO (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (324, 'LA BIJA (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (325, 'LA CUEVA (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (326, 'PLATANAL (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (327, 'QUITA SUEÑO (DM)', 28);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (328, 'VILLA LA MATA', 28);
INSERT INTO provincias (id, nombre) VALUES (29, 'SANTIAGO DE LOS CABALLEROS');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (329, 'BAITOA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (330, 'CANABACOA ABAJO (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (331, 'CANCA LA PIEDRA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (332, 'EL CAIMITO (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (333, 'EL LIMON (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (334, 'EL RUBIO (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (335, 'GUAYABAL (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (336, 'HATO DEL YAQUE (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (337, 'JANICO', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (338, 'JUNCALITO (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (339, 'LA CANELA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (340, 'LAS CUESTA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (341, 'LAS PALOMAS (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (342, 'LAS PLACETAS (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (343, 'LICEY AL MEDIO', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (344, 'PALMAR ARRIBA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (345, 'PEDRO GARCIA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (346, 'PUÑAL', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (347, 'SABANA IGLESIA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (348, 'SAN FRANCISCO DE JACAGUA (DM)', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (349, 'SAN JOSE DE LAS MATAS', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (350, 'SANTIAGO DE LOS CABALLEROS', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (351, 'TAMBORIL', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (352, 'VILLA BISONO -NAVARRETE-', 29);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (353, 'VILLA GONZALEZ', 29);
INSERT INTO provincias (id, nombre) VALUES (30, 'SANTIAGO RODRIGUEZ');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (354, 'MONCION', 30);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (355, 'SAN IGNACIO DE SABANETA', 30);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (356, 'VILLA LOS ALMACIGOS', 30);
INSERT INTO provincias (id, nombre) VALUES (31, 'SANTO DOMINGO');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (357, 'BOCA CHICA', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (358, 'HATO VIEJO (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (359, 'LA CALETA (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (360, 'LA CUABA (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (361, 'LA GUAYIGA (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (362, 'LA VICTORIA (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (363, 'LOS ALCARRIZOS', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (364, 'PALMAREJO (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (365, 'PANTOJA (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (366, 'PEDRO BRAND', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (367, 'SAN ANTONIO DE GUERRA', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (368, 'SAN LUIS (DM)', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (369, 'SANTO DOMINGO ESTE', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (370, 'SANTO DOMINGO NORTE', 31);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (371, 'SANTO DOMINGO OESTE', 31);
INSERT INTO provincias (id, nombre) VALUES (32, 'VALVERDE');
INSERT INTO municipios (id, nombre, provincia_id) VALUES (372, 'AMINA (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (373, 'BOCA DE MAO (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (374, 'CRUCE DE GUAYACANES (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (375, 'ESPERANZA', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (376, 'GUATAPANAL (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (377, 'JAIBON (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (378, 'JAIÑAN (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (379, 'JICOME (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (380, 'LA CAYA (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (381, 'LAGUNA SALADA', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (382, 'MAIZAL (DM)', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (383, 'MAO', 32);
INSERT INTO municipios (id, nombre, provincia_id) VALUES (384, 'PARADERO (DM)', 32);